<Project ToolsVersion="3.5" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />
  
  <ItemGroup>
    
    <Module Include="Axiom\axiom.core.module">
      <Configuration>Debug</Configuration>
      <Platform>x86</Platform>
    </Module>
	<Module Include="Axiom\axiom.core.module">
	  <Configuration>Release</Configuration>
	  <Platform>x86</Platform>
	</Module>
	  
    <Module Include="Axiom\axiom.core.module">
      <Configuration>Debug</Configuration>
      <Platform>Xbox</Platform>
    </Module>
    <Module Include="Axiom\axiom.core.module">
      <Configuration>Release</Configuration>
      <Platform>Xbox</Platform>
    </Module>

    <Module Include="Axiom.Framework\axiom.framework.module">
      <Configuration>Debug</Configuration>
      <Platform>x86</Platform>
    </Module>
    <Module Include="Axiom.Framework\axiom.framework.module">
	  <Configuration>Release</Configuration>
	  <Platform>x86</Platform>
	</Module>
	  
    <Module Include="Axiom.Framework\axiom.framework.module">
      <Configuration>Debug</Configuration>
      <Platform>Xbox</Platform>
    </Module>
    <Module Include="Axiom.Framework\axiom.framework.module">
      <Configuration>Release</Configuration>
      <Platform>Xbox</Platform>
    </Module>
	
    <Module Include="AxiomDemos\axiom.demos.module">
      <Configuration>Release</Configuration>
      <Platform>x86</Platform>
      <Properties>
        RenderSystem=DirectX
      </Properties>
    </Module>

    <Module Include="AxiomDemos\axiom.demos.module">
      <Configuration>Release</Configuration>
      <Platform>x86</Platform>
      <Properties>
        RenderSystem=OpenGL
      </Properties>
    </Module>

    <Module Include="AxiomDemos\axiom.demos.module">
      <Configuration>Release</Configuration>
      <Platform>x86</Platform>
      <Properties>
        RenderSystem=Xna
      </Properties>
    </Module>

    <Module Include="AxiomDemos\axiom.demos.module">
      <Configuration>Release</Configuration>
      <Platform>Xbox</Platform>
      <Properties>
        RenderSystem=Xna
      </Properties>
    </Module>

    <Module Include="Samples\axiom.samples.module">
      <Configuration>Release</Configuration>
      <Platform>x86</Platform>
      <Properties>
        Framework=DotNet
      </Properties>
    </Module>

    <Module Include="Samples\axiom.samples.module">
      <Configuration>Release</Configuration>
      <Platform>x86</Platform>
      <Properties>
        Framework=Mono
      </Properties>
    </Module>

    <Module Include="Samples\axiom.samples.module">
      <Configuration>Release</Configuration>
      <Platform>Xbox</Platform>
      <Properties>
        Framework=DotNet
      </Properties>
    </Module>
    
    <Module Include="Tests\axiom.tests.module">
      <Configuration>Release</Configuration>
      <Platform>x86</Platform>
    </Module>
  </ItemGroup>

  <ItemGroup>
    <File Include="..\Media\**\*" >
      <ImagePath>$(ImagePath)\demos\media</ImagePath>
    </File>
  </ItemGroup>

</Project>
