<Project ToolsVersion="3.5" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />
  
  <ItemGroup>
    
    <Module Include="Axiom\axiom.core.module">
      <Configuration>Debug</Configuration>
      <Platform>x86</Platform>
    </Module>
	<Module Include="Axiom\axiom.core.module">
  	  <Configuration>Release</Configuration>
  	  <Platform>x86</Platform>
	</Module>

    <Module Include="Axiom\axiom.core.module">
      <Configuration>Debug</Configuration>
      <Platform>Xbox</Platform>
    </Module>
    <Module Include="Axiom\axiom.core.module">
      <Configuration>Release</Configuration>
      <Platform>Xbox</Platform>
    </Module>

    <Module Include="AxiomDemos\axiom.samples.module">
      <Configuration>Release</Configuration>
      <Platform>x86</Platform>
      <Properties>
        RenderSystem=DirectX
      </Properties>
    </Module>

    <Module Include="AxiomDemos\axiom.samples.module">
      <Configuration>Release</Configuration>
      <Platform>x86</Platform>
      <Properties>
        RenderSystem=OpenGL
      </Properties>
    </Module>

    <Module Include="AxiomDemos\axiom.samples.module">
      <Configuration>Release</Configuration>
      <Platform>x86</Platform>
      <Properties>
        RenderSystem=Xna
      </Properties>
    </Module>

    <Module Include="AxiomDemos\axiom.samples.module">
      <Configuration>Release</Configuration>
      <Platform>Xbox</Platform>
      <Properties>
        RenderSystem=Xna
      </Properties>
    </Module>

    <Module Include="Tests\axiom.tests.module">
      <Configuration>Release</Configuration>
      <Platform>x86</Platform>
    </Module>
  </ItemGroup>

  <ItemGroup>
	<File Include="..\Media\**\*" >
      <ImagePath>$(ImagePath)\samples\media</ImagePath>
    </File>
  </ItemGroup>
  
</Project>
