/***************************************************************************************
 * This shader was generated by a tool; any changes made to this file may be lost
 * Axiom Fixed Function Emulation Layer
 * Vertex Program Entry Point : VS
 * Fragment Program Entry Point : FP
 * Vertex Buffer Delcaration : Float3 Position0;
Float3 Normal0;
Float2 TexCoords0;

 * Fixed Function State : Axiom.RenderSystems.Xna.FixedFunctionEmulation.FixedFunctionState
 ***************************************************************************************/

struct VS_OUTPUT
{
	float4 Pos : POSITION;
	float2 Texcoord0 : TEXCOORD0;
	float4 Color: COLOR0;
	float4 ColorSpec: COLOR1;
};

float4 main_fp( VS_OUTPUT input, uniform sampler2D Texture0 : register(s0) ) : COLOR
{
	float4 finalColor= input.Color + input.ColorSpec;
	{
		float4 texColor = tex2D(Texture0, input.Texcoord0);
		float4 source1 = texColor;
		float4 source2 = finalColor;
		finalColor = source1 /* * source2 */;
	}
	return finalColor;
}
