<Project ToolsVersion="3.5" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />

  <ItemGroup>
    <!-- The path of a project to be built. -->
    <CSharpProject Include="Axiom.RenderSystems.DirectX9.csproj">
      <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    </CSharpProject>

    <!-- The path of a built file to be copied to the "image" directory. -->
    <File Include="bin\x86\Axiom.RenderSystems.DirectX9.dll">
      <ImagePath>bin\$(Platform)\$(Configuration)</ImagePath>
    </File>

    <File Include="bin\x86\Axiom.RenderSystems.DirectX9.pdb" Condition="'$(Configuration)'=='Debug'">
      <ImagePath>bin\$(Platform)\$(Configuration)</ImagePath>
    </File>

    <File Include="bin\x86\Axiom.RenderSystems.DirectX9.xml"  Condition="'$(Configuration)'=='Release'">
      <ImagePath>bin\$(Platform)\$(Configuration)</ImagePath>
    </File>

  </ItemGroup>

</Project>