trigger:
  - master
  - develop
pr:
  - master
  - develop
  
variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
  
strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
      configuration: "linux_$(buildConfiguration)"
    mac:
      imageName: "macos-latest"
      configuration: "MacOS_$(buildConfiguration)"
    windows:
      imageName: "windows-latest"
      configuration: $(buildConfiguration)
  
pool:
  vmImage: $(imageName)
        
steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: true
    workingDirectory: 'Source'
  displayName: 'Use .NET Core SDK'
  env:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

- task: NuGetToolInstaller@1
  displayName: Install NuGet
      
- task: DotNetCoreCLI@2
  inputs:
    command: custom
    custom: tool
    arguments: 'install -g Cake.Tool'
  env:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  displayName: Install dotnet Cake Build Tool
   
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '.\build.ps1 -Script build.cake -Target Build -Configuration $(configuration) -Verbosity Diagnostic --settings_skipverification=true'
    pwsh: true
  displayName: Build Product
