trigger:
  - master
  - develop
pr:
  - master
  - develop
  
variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
  DOTNET_SDK_VERSION: '3.0.100-preview9-013775'
  
strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
      configuration: "linux_$(buildConfiguration)"
    mac:
      imageName: "macos-latest"
      configuration: "MacOS_$(buildConfiguration)"
    windows:
      imageName: "windows-latest"
      configuration: $(buildConfiguration)
  
pool:
  vmImage: $(imageName)
        
steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '$(DOTNET_SDK_VERSION)'
  displayName: 'Use .NET Core SDK $(DOTNET_SDK_VERSION)'
    
- task: NuGetToolInstaller@1
  displayName: Install NuGet
      
- task: DotNetCoreCLI@2
  inputs:
    command: custom
    custom: tool
    arguments: 'install -g Cake.Tool'
  env:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  displayName: Install dotnet Cake Build Tool
   
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '.\build.ps1 -Script build.cake -Target Build -Configuration $(configuration) -Verbosity Diagnostic --settings_skipverification=true'
    pwsh: true
  displayName: Build Product
