trigger:
  - master
pr:
  - master
  
variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
  DOTNET_SDK_VERSION: '2.1.604'
  
strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
    mac:
      imageName: "macos-latest"
    windows:
      imageName: "vs2017-win2016"
  
pool:
  vmImage: $(imageName)
        
steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core SDK $(DOTNET_SDK_VERSION)'
  inputs:
    version: '$(DOTNET_SDK_VERSION)'
    
- task: NuGetToolInstaller@1
  displayName: Install NuGet
      
- task: DotNetCoreCLI@2
  displayName: Install dotnet Cake Build Tool
  inputs:
    command: custom
    custom: tool
    arguments: 'install -g Cake.Tool'
  env:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  
- task: DotNetCoreCLI@2
  displayName: Run dotnet Cake Bootstrapper
  inputs:
    command: custom
    custom: cake
    arguments: 'build.cake --bootstrap'
  env:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

- task: DotNetCoreCLI@2
  displayName: Build Product
  inputs:
    command: custom
    custom: cake
    arguments: '--target=build --configuration=$(BuildConfiguration)'
  env:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1