<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
	<Import Project="$(RootDir)\tools\build\Module.targets" />
	<ItemGroup>
		<Svn Include="$(RootDir)" />
		<Version Include="Projects\Axiom\version.txt" />
		<AssemblyInfoTemplate Include="Projects\Axiom\GlobalAssemblyInfo.cs.in" >
			<OutputFile>Projects\Axiom\GlobalAssemblyInfo.cs</OutputFile>
		</AssemblyInfoTemplate>
		<AssemblyInfoTemplate Include="Projects\Axiom\version.txt.in" >
			<OutputFile>Projects\Axiom\version.txt</OutputFile>
		</AssemblyInfoTemplate>
	</ItemGroup>

	<Import Project="$(AxiomBuildTasksPath)\Axiom.Build.Version.Targets" />

	<ItemGroup>
		<LicenseFile Include="license.txt" />

		<File Include="credits.txt" />

		<Feature Include="NO_ILMERGE" Condition="'$(SkipILMerge)'=='true'" />
		<Feature Include="DOTNET40" Condition="'$(DotNetFrameworkVersion)'=='4.0'" />
	</ItemGroup>

	<ItemGroup Condition="'$(SkipSources)'!='true'">
		<Feature Include="FEATURE_SOURCES" />
	</ItemGroup>

	<Target Name="BeforeImage"
					DependsOnTargets="BuildSourcesFile" />

	<Target Name="BuildSourcesFile"
			DependsOnTargets="UpdateVersionTxtFile"
					Condition="'$(SkipSources)'!='true'">

		<SvnInfo WorkingCopy="$(RootDir)" >
			<Output TaskParameter="SvnRepository" ItemName="SvnRepositoryItem" />
			<Output TaskParameter="SvnRevision" ItemName="SvnRevisionItem" />
		</SvnInfo>
		<PropertyGroup>
			<SvnRepository>@(SvnRepositoryItem)</SvnRepository>
			<SvnRevision>@(SvnRevisionItem)</SvnRevision>
		</PropertyGroup>

		<Message Text="SvnRepository : $(SvnRepository)" />
		<Message Text="SvnRevision : $(SvnRevision)" />
		<Error Text="Could not parse SVN info.  Use /p:SkipSources=true to skip generating sources.txt."
					 Condition="'$(SvnRepository)'=='' or '$(SvnRevision)'==''" />

		<WriteLinesToFile File="$(ModuleImageDir)\Sources.txt"
											Overwrite="true"
											Lines="Axiom v$(AssemblyVersion) was generated from the following sources.%0D%0A%0D%0ASubversion Repository: $(SvnRepository)%0D%0A           Revision: $(SvnRevision)%0D%0A%0D%0APlease visit the following Url for checkout instructions.%0D%0A  http://sourceforge.net/scm/?type=svn&amp;group_id=84345%0D%0A%0D%0AAlso refer to the wiki for information about how to debug with symbols and source code.%0D%0A  http://www.axiom3d.net/wiki/debugging_with_symbols_and_source_code" />
	</Target>


</Project>