sampler RT: register(s0);

float4 sharpenEdges_fp(float2 iTexCoord: TEXCOORD0) : COLOR {

	float2 vTexelSize = 0.005;

	float2 usedTexelED[8] = {
		-1, -1,
		 0, -1,
		 1, -1,
		-1,  0,
		 1,  0,
		-1,  1,
		 0,  1,
	     1,  1,
	};

	float4 cAvgColor= 9 * tex2D (RT, iTexCoord);

	for(int t=0; t<8; t++)
		cAvgColor -= tex2D(RT, iTexCoord + vTexelSize * usedTexelED[t]);

	return cAvgColor;
}
