package = newpackage()
package.name = "Plugin_GuiElements"
package.language = "c#"
package.kind = "dll"
package.buildflags = { "unsafe" }
package.target = "Axiom.Gui.Elements"
package.defines = { "TRACE" } 
package.config["Debug"].defines = { "DEBUG" }
package.links = { "System", "Engine", "MathLib" }
package.files = { matchfiles("*.cs") }