<Project ToolsVersion="3.5" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />

  <PropertyGroup>
    <Framework>$(Framework)</Framework>
    <ProjectBase>Axiom.Samples.Browser</ProjectBase>
    <ProjectFile Condition="'$(Framework)|$(Platform)'=='DotNet|x86'">$(ProjectBase).Win32.csproj</ProjectFile>
    <ProjectFile Condition="'$(Framework)'=='Mono'">$(ProjectBase).Linux.csproj</ProjectFile>
    <!--ProjectFile Condition="'$(Platform)'=='Xbox'">$(ProjectBase).$(Platform).csproj</ProjectFile-->
    <ImagePath Condition="'$(Framework)'=='DotNet'">samples\Net35</ImagePath>
    <ImagePath Condition="'$(Framework)'=='Mono'">samples\Mono</ImagePath>
    <!--ImagePath Condition="'$(Platform)'=='Xbox'">samples\Xbox</ImagePath-->
    <OutputPath>bin\$(Platform)\$(Configuration)</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <!-- The path of a project to be built. -->
    <CSharpProject Include="$(ProjectFile)" >
      <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
      <Platform Condition="'$(Platform)'=='Xbox'">$(Platform) 360</Platform>
      <OutputPath>$(OutputPath)</OutputPath>
      <WarningLevel Condition="'$(Configuration)'=='Debug'">4</WarningLevel>
      <WarningLevel Condition="'$(Configuration)'=='Release'">0</WarningLevel>
    </CSharpProject>

    <!-- The path of a built file to be copied to the "image" directory. -->
    <File Include="$(OutputPath)\$(ProjectBase).exe" Condition="'$(Platform)'!='x86'" >
      <ImagePath>$(ImagePath)</ImagePath>
    </File>
    
    <!-- Binary Dependencies -->

    <!-- Platform Manager -->
    
    <File Include="$(ImageDir)\bin\$(Platform)\$(Configuration)\Axiom.Platforms.Win32.dll" Condition="'$(Framework)'=='DotNet'">
      <ImagePath>$(ImagePath)</ImagePath>
    </File>

    <File Include="$(ImageDir)\bin\$(Platform)\$(Configuration)\Axiom.Platforms.OpenTK.dll" Condition="'$(Framework)'=='Mono'">
      <ImagePath>$(ImagePath)</ImagePath>
    </File>

    <!-- RenderSystem  -->

    <File Include="$(ImageDir)\bin\$(Platform)\$(Configuration)\Axiom.RenderSystems.DirectX9.dll" Condition="'$(Framework)'!='Mono'">
      <ImagePath>$(ImagePath)</ImagePath>
    </File>
    
    <File Include="$(ImageDir)\bin\$(Platform)\$(Configuration)\Axiom.RenderSystems.Xna.dll" Condition="'$(Framework)'!='Mono'">
      <ImagePath>$(ImagePath)</ImagePath>
    </File>
    <File Include="$(ImageDir)\bin\$(Platform)\$(Configuration)\Axiom.RenderSystems.Xna.Content.dll" Condition="'$(Framework)'!='Mono'">
      <ImagePath>$(ImagePath)</ImagePath>
    </File>

    <File Include="$(ImageDir)\bin\$(Platform)\$(Configuration)\Axiom.RenderSystems.OpenGL.OpenTK.dll" >
      <ImagePath>$(ImagePath)</ImagePath>
    </File>

    <!-- Scene Managers -->
    
    <File Include="$(ImageDir)\bin\$(Platform)\$(Configuration)\Axiom.SceneManagers.Bsp.dll" >
      <ImagePath>$(ImagePath)</ImagePath>
    </File>

    <File Include="$(ImageDir)\bin\$(Platform)\$(Configuration)\Axiom.SceneManagers.Octree.dll" >
      <ImagePath>$(ImagePath)</ImagePath>
    </File>

    <File Include="$(ImageDir)\bin\$(Platform)\$(Configuration)\Axiom.SceneManagers.PortalConnected.dll" Condition="'$(Platform)'=='x86'" >
      <ImagePath>$(ImagePath)</ImagePath>
    </File>

    <!-- Plugins -->

    <File Include="$(ImageDir)\bin\$(Platform)\$(Configuration)\Axiom.Plugins.ParticleFX.dll" >
      <ImagePath>$(ImagePath)</ImagePath>
    </File>

    <File Include="$(ImageDir)\bin\$(Platform)\$(Configuration)\Axiom.Plugins.DeviLCodecs.dll" Condition="'$(Platform)'=='x86'" >
      <ImagePath>$(ImagePath)</ImagePath>
    </File>

    <File Include="$(ImageDir)\bin\$(Platform)\$(Configuration)\Axiom.Plugins.CgProgramManager.dll" Condition="'$(Platform)'=='x86'" >
      <ImagePath>$(ImagePath)</ImagePath>
    </File>

  </ItemGroup>

</Project>
