<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0" 
				xmlns:MSHelp="http://msdn.microsoft.com/mshelp"
				xmlns:ddue="http://ddue.schemas.microsoft.com/authoring/2003/5"
				xmlns:xlink="http://www.w3.org/1999/xlink"
        xmlns:msxsl="urn:schemas-microsoft-com:xslt">

  <xsl:import href="globalTemplates.xsl"/>
  <xsl:template name="upperBodyStuff">
    <input type="hidden" id="userDataCache" class="userDataStyle"/>
    <input type="hidden" id="hiddenScrollOffset"/>
    
    <xsl:call-template name="commonImages"/>

    <xsl:call-template name="bodyHeader"/>
    
  </xsl:template>

  <xsl:template name="bodyHeader">
    <div id="header">
      <xsl:call-template name="bodyHeaderTopTable"/>

      <xsl:call-template name="bodyHeaderBottomTable"/>

      <xsl:if test="($group='type' or $group='member') and not($pseudo)">
        <xsl:call-template name="languageSpan"/>
      </xsl:if>

      <!-- include the member options dropdown on memberlist topics -->
      <xsl:if test="$pseudo and not($subgroup='DerivedTypeList' or $group='root' or $group='member')">
        <xsl:call-template name="membersOptionsSpan"/>
      </xsl:if>
    </div>
  </xsl:template>

  <xsl:template name="bodyHeaderTopTable">
    <table width="100%" id="topTable">
      <tr id="headerTableRow1">
        <td align="left">
          <span id="runningHeaderText">
            <include item="productTitle"/>
          </span>
        </td>
      </tr>
      <tr id="headerTableRow2">
        <td align="left">
          <span id="nsrTitle">
            <xsl:call-template name="topicTitleDecorated"/>
          </span>
        </td>
      </tr>
      <tr id="headerTableRow3">
        <td>
          <xsl:call-template name="headerRowLinks"/>
        </td>
      </tr>
    </table>
  </xsl:template>

  <xsl:template name="headerRowLinks">
    <!-- most mref topics get autogenerated see also links to see also section -->
    
    <xsl:if test="$hasSeeAlsoSection">
      
      <a href="#seealsoToggle" onclick="OpenSection(seealsoToggle)">
        <xsl:text/>
        <include item="SeeAlso"/>
        <xsl:text/>
      </a>&#160;
      
    </xsl:if>
    
    <!-- include Example link if there's an Example section -->
    <xsl:choose>
      <xsl:when test="$examplesSection">
        <a href="#exampleToggle" onclick="OpenSection(exampleToggle)">
          <xsl:text/>
          <include item="Example"/>
          <xsl:text/>
        </a>&#160;
      </xsl:when>
    </xsl:choose>

    <!-- class, structure, and interface About topics get link to Members topic (unless the doc model has the all members lists on the type topic) -->
    <xsl:if test="/document/reference/elements/@allMembersTopicId">
      <referenceLink target="{/document/reference/elements/@allMembersTopicId}">
        <include item="membersTitle"/>
      </referenceLink>
    </xsl:if>
    
  </xsl:template>


  <xsl:template name="bodyHeaderBottomTable">
    <table width="100%" id="bottomTable" cellspacing="0" cellpadding="0">
      <tr>
        <td>
          <span onclick="ExpandCollapseAll(toggleAllImage)" style="cursor:default;" onkeypress="ExpandCollapseAll_CheckKey(toggleAllImage, event)" tabindex="0">
            <img ID="toggleAllImage" class="toggleAll" alt="CollapseAll image">
              <includeAttribute name="src" item="iconPath">
                <parameter>collall.gif</parameter>
              </includeAttribute>
            </img>
            <label id="collapseAllLabel" for="toggleAllImage" style="display: none;">
              <include item="collapseAll"/>
            </label>
            <label id="expandAllLabel" for="toggleAllImage" style="display: none;">
              <include item="expandAll"/>
            </label>
            <xsl:text>&#160;</xsl:text>
          </span>

          <xsl:if test="($group='type' or $group='member') and not($pseudo)">
            <xsl:call-template name="languageFilterToolTip"/>
          </xsl:if>

          <!-- include the member options dropdown on memberlist topics -->
          <xsl:if test="$pseudo and not($subgroup='DerivedTypeList' or $group='root' or $group='member')">
            <xsl:call-template name="membersOptionsFilterToolTip"/>
          </xsl:if>
        </td>
      </tr>
    </table>
  </xsl:template>

  <xsl:template name="membersOptionsSpan">
    <div id="membersOptionsSpan">
      <input id="inheritedCheckbox" type='checkbox' name="membersOptionsFilter" onClick="SetMembersOptions(this)"/>
      <label class="membersOptionsFilter" for="inheritedCheckbox">
        <include item="includeInheritedMembers"/>
      </label>
      <br/>
      <input id="protectedCheckbox" type='checkbox' name="membersOptionsFilter" onClick="SetMembersOptions(this)"/>
      <label class="membersOptionsFilter" for="protectedCheckbox">
        <include item="includeProtectedMembers"/>
      </label>
      <br/>
      <input id="netcfCheckbox" type='checkbox' name="membersOptionsFilter" onClick="SetMembersOptions(this)"/>
      <label class="membersOptionsFilter" for="netcfCheckbox">
        <include item="netcfMembersOnly"/>
      </label>
      <br/>
    </div>
  </xsl:template>
  
  <xsl:template name="membersOptionsFilterToolTip">
    <span id="membersOptionsFilterToolTip" style="cursor:default;" onmouseover="membersOptionsFilterImage.src=dropDownHoverImage.src;" onmouseout="membersOptionsFilterImage.src=dropDownImage.src;" tabindex="0">
      <img id="membersOptionsFilterImage" alt="DropDown image">
        <includeAttribute name="src" item="iconPath">
          <parameter>drpdown.gif</parameter>
        </includeAttribute>
      </img>
      <label id="showAllMembersLabel" for="membersOptionsFilterImage" style="display: none;">
        <include item="membersOptionsShowAll"/>
      </label>
      <label id="filteredMembersLabel" for="membersOptionsFilterImage" style="display: none;">
        <include item="membersOptionsFiltered"/>
      </label>
    </span>
  </xsl:template>
  
  <xsl:template name="languageFilterToolTip">
    <span id="languageFilterToolTip" style="cursor:default;" onmouseover="languageFilterImage.src=dropDownHoverImage.src;" onmouseout="languageFilterImage.src=dropDownImage.src;" tabindex="0">
      <img id="languageFilterImage" alt="DropDown image">
        <includeAttribute name="src" item="iconPath">
          <parameter>drpdown.gif</parameter>
        </includeAttribute>
      </img>
      <label id="showAllLabel" for="languageFilterImage" style="display: none;">
        <include item="languageFilter">
          <parameter>
            <include item="all"/>
          </parameter>
        </include>
      </label>
      <label id="multipleLabel" for="languageFilterImage" style="display: none;">
        <include item="languageFilter">
          <parameter>
            <include item="multiple"/>
          </parameter>
        </include>
      </label>
      <label id="vbLabel" for="languageFilterImage" style="display: none;">
        <include item="languageFilter">
          <parameter>
            <include item="VisualBasic"/>
          </parameter>
        </include>
      </label>
      <label id="csLabel" for="languageFilterImage" style="display: none;">
        <include item="languageFilter">
          <parameter>
            <include item="CSharp"/>
          </parameter>
        </include>
      </label>
      <label id="cLabel" for="languageFilterImage" style="display: none;">
        <include item="languageFilter">
          <parameter>
            <include item="ManagedCPlusPlus"/>
          </parameter>
        </include>
      </label>
      <label id="jsharpLabel" for="languageFilterImage" style="display: none;">
        <include item="languageFilter">
          <parameter>
            <include item="JSharp"/>
          </parameter>
        </include>
      </label>
      <label id="jsLabel" for="languageFilterImage" style="display: none;">
        <include item="languageFilter">
          <parameter>
            <include item="JScript"/>
          </parameter>
        </include>
      </label>
      <label id="xamlLabel" for="languageFilterImage" style="display: none;">
        <include item="languageFilter">
          <parameter>
            <include item="XAML"/>
          </parameter>
        </include>
      </label>
    </span>
  </xsl:template>
  
  <xsl:template name="languageSpan">
    <div id="languageSpan">
      <input id="vbDeclarationCheckbox" type='checkbox' name="languageFilter" onClick="SetLanguage(this)"/>
      <label class="languageFilter" for="vbDeclarationCheckbox">
        <include item="VisualBasicDeclaration"/>
      </label>
      <br/>
      <input id="vbUsageCheckbox" type='checkbox' name="languageFilter" onClick="SetLanguage(this)"/>
      <label class="languageFilter" for="vbUsageCheckbox">
        <include item="VisualBasicUsage"/>
      </label>
      <br/>
      <input id="csCheckbox" type='checkbox' name="languageFilter" onClick="SetLanguage(this)"/>
      <label class="languageFilter" for="csCheckbox">
        <include item="CSharp"/>
      </label>
      <br/>
      <input id="cCheckbox" type='checkbox' name="languageFilter" onClick="SetLanguage(this)"/>
      <label class="languageFilter" for="cCheckbox">
        <include item="ManagedCPlusPlus"/>
      </label>
      <br/>
      <input id="jsharpCheckbox" type='checkbox' name="languageFilter" onClick="SetLanguage(this)"/>
      <label class="languageFilter" for="jsharpCheckbox">
        <include item="JSharp"/>
      </label>
      <br/>
      <input id="jsCheckbox" type='checkbox' name="languageFilter" onClick="SetLanguage(this)"/>
      <label class="languageFilter" for="jsCheckbox">
        <include item="JScript"/>
      </label>
      <br/>
      <input id="xamlCheckbox" type='checkbox' name="languageFilter" onClick="SetLanguage(this)"/>
      <label class="languageFilter" for="xamlCheckbox">
        <include item="XAML"/>
      </label>
      <br/>
    </div>
  </xsl:template>
    


  <!-- image links 
current ndppick XSLT behavior:
expandAllImage - all
dropDownImage - not namespace or derivedTypeList
dropDownHoverImage -  not namespace or derivedTypeList
collapseImage - all
expandImage - all
collapseAllImage - all
copyImage - overview (not namespace); list (only overload lists ctor, method, prop)
copyHoverImage - overview (not namespace); list (only overload lists ctor, method, prop)
  -->
  <xsl:template name="commonImages">
    <img id="collapseImage" style="display:none; height:0; width:0;" alt="Collapse image">
      <includeAttribute name="src" item="iconPath">
        <parameter>collapse_all.gif</parameter>
      </includeAttribute>
    </img>
    <img id="expandImage" style="display:none; height:0; width:0;" alt="Expand image">
      <includeAttribute name="src" item="iconPath">
        <parameter>expand_all.gif</parameter>
      </includeAttribute>
    </img>
    <img id="collapseAllImage" style="display:none; height:0; width:0;" alt="CollapseAll image">
      <includeAttribute name="src" item="iconPath">
        <parameter>collall.gif</parameter>
      </includeAttribute>
    </img>
    <img id="expandAllImage" style="display:none; height:0; width:0;" alt="ExpandAll image">
      <includeAttribute name="src" item="iconPath">
        <parameter>expall.gif</parameter>
      </includeAttribute>
    </img>
    <img id="dropDownImage" style="display:none; height:0; width:0;" alt="DropDown image">
      <includeAttribute name="src" item="iconPath">
        <parameter>drpdown.gif</parameter>
      </includeAttribute>
    </img>
    <img id="dropDownHoverImage" style="display:none; height:0; width:0;" alt="DropDownHover image">
      <includeAttribute name="src" item="iconPath">
        <parameter>drpdown_orange.gif</parameter>
      </includeAttribute>
    </img>
    <xsl:if test="($group='type' or $group='member') and not($pseudo)">
      <img id="copyImage" style="display:none; height:0; width:0;" alt="Copy image">
        <includeAttribute name="src" item="iconPath">
          <parameter>copycode.gif</parameter>
        </includeAttribute>
      </img>
      <img id="copyHoverImage" style="display:none; height:0; width:0;" alt="CopyHover image">
        <includeAttribute name="src" item="iconPath">
          <parameter>copycodeHighlight.gif</parameter>
        </includeAttribute>
      </img>
    </xsl:if>
  </xsl:template>

  
</xsl:stylesheet>