/***************************************************************************************
 * This shader was generated by a tool; any changes made to this file may be lost
 * Axiom Fixed Function Emulation Layer
 * Fragment Program Entry Point : FP
 ***************************************************************************************/

float4  FogColor;

struct VS_OUTPUT
{
	float4 Pos : POSITION;
	float2 Texcoord0 : TEXCOORD0;
	float4 Color: COLOR0;
	float4 ColorSpec: COLOR1;
	float4 fogDist: COLOR2;
};

sampler2D Texture0 : register(s0);

float4 FP( VS_OUTPUT input ) : COLOR
{
	float4 finalColor= input.Color + input.ColorSpec;
	{
		float4 texColor=float4(1.0,1.0,1.0,1.0);
		texColor  = tex2D(Texture0, input.Texcoord0);
		float4 source1 = texColor;
		float4 source2 = finalColor;
		finalColor = source1 * source2;
	}
	finalColor = input.fogDist * finalColor + (1.0 - input.fogDist) * FogColor;
	return finalColor;
}
