<Project ToolsVersion="3.5" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />

  <ItemGroup>
    <Module Include="Source\Browser\WinForm\axiom.demos.browser.winform.module" Condition="'$(Platform)'=='x86'" />
    <Module Include="Source\Browser\Xbox\axiom.demos.browser.xbox.module" Condition="'$(Platform)'=='Xbox'" />
    
  </ItemGroup>
  
</Project>
