<Project ToolsVersion="3.5" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />

  <ItemGroup>
    <Module Include="Browser\axiom.samples.browser.module" />
    <!--
    <Module Include="Browser\axiom.samples.common.module" />
    <Module Include="Browser\axiom.samples.bezierpatch.module" />
    <Module Include="Browser\axiom.samples.bsp.module" />
    <Module Include="Browser\axiom.samples.cameratracking.module" />
    <Module Include="Browser\axiom.samples.charactersample.module" />
    <Module Include="Browser\axiom.samples.dynamictexture.module" />
    <Module Include="Browser\axiom.samples.ocean.module" />
    <Module Include="Browser\axiom.samples.particlefx.module" />
    <Module Include="Browser\axiom.samples.spheremapping.module" />
    <Module Include="Browser\axiom.samples.volumetexture.module" />
    -->
  </ItemGroup>
  
</Project>
