<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(RootDir)\tools\build\Module.targets" />
  
  <ItemGroup>
    <CSharpProject Include="Browser\Axiom.Samples.Browser.Win32$(ProjectVariant).csproj" />
    <CSharpProject Include="Browser\Axiom.Samples.Browser.Linux$(ProjectVariant).csproj" />

    <CSharpProject Include="Media\Axiom.Samples.Media$(ProjectVariant).csproj" />
	
    <CSharpProject Include="Core\Axiom.Samples.Core$(ProjectVariant).csproj" />
     
    <AssemblyFile Include="bin\win32\*.dll">
      <ImagePath>samples\win32</ImagePath>
    </AssemblyFile>
    <AssemblyFile Include="bin\win32\*.exe">
      <ImagePath>samples\win32</ImagePath>
    </AssemblyFile>
    <ConfigFile Include="bin\win32\*.config">
      <ImagePath>samples\win32</ImagePath>
    </ConfigFile>
	
    <AssemblyFile Include="bin\linux\*.dll">
      <ImagePath>samples\linux</ImagePath>
    </AssemblyFile>
    <AssemblyFile Include="bin\linux\*.exe">
      <ImagePath>samples\linux</ImagePath>
    </AssemblyFile>
    <ConfigFile Include="bin\linux\*.config">
      <ImagePath>samples\linux</ImagePath>
    </ConfigFile>
		
    <AssemblyFile Include="bin\samples\Axiom.Samples.Core.dll">
      <ImagePath>samples\samples</ImagePath>
    </AssemblyFile>

    <AssemblyFile Include="Media\**\*" Exclude="Media\**\*.csproj;Media\out\**\*" >
      <ImagePath>samples\media</ImagePath>
    </AssemblyFile>

  </ItemGroup>
  
  <Target 
    Name="AfterImage" 
    DependsOnTargets="SamplesImage_FixConfig" />

  <Target
    Name="SamplesImage_FixConfig">
	
	<FileUpdate Files="$(ModuleImageDir)\samples\win32\Axiom.Samples.Browser.exe.config"
               Regex="\.\./\.\./"
               ReplacementText="../" />
    <FileUpdate Files="$(ModuleImageDir)\samples\linux\Axiom.Samples.Browser.exe.config"
               Regex="\.\./\.\./"
               ReplacementText="../" />			   
  </Target>
</Project>