<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(RootDir)\tools\build\Module.targets" />
  <Import Project="axiom.common.version.module" />
  
  <ItemGroup>
    <CSharpProject Include="Engine\Axiom$(ProjectVariant).csproj" />
    <CSharpProject Include="Platforms\Win32\Axiom.Platforms.Win32$(ProjectVariant).csproj" />
    <CSharpProject Include="Platforms\OpenTK\Axiom.Platforms.OpenTK$(ProjectVariant).csproj" />
    <CSharpProject Include="RenderSystems\DirectX9\Axiom.RenderSystems.DirectX9$(ProjectVariant).csproj" />
    <CSharpProject Include="RenderSystems\OpenGL\Axiom.RenderSystems.OpenGL.OpenTK$(ProjectVariant).csproj" />
    <CSharpProject Include="SceneManagers\BSP\Axiom.SceneManagers.BSP$(ProjectVariant).csproj" />
    <CSharpProject Include="SceneManagers\Octree\Axiom.SceneManagers.Octree$(ProjectVariant).csproj" />
    <CSharpProject Include="SceneManagers\PCZ\Axiom.SceneManagers.PortalConnected$(ProjectVariant).csproj" />
    <CSharpProject Include="Plugins\Axiom.Plugins.FreeImageCodecs\Axiom.Plugins.FreeImageCodecs$(ProjectVariant).csproj" />
    <CSharpProject Include="Plugins\Axiom.Plugins.SystemDrawingCodecs\Axiom.Plugins.SystemDrawingCodecs$(ProjectVariant).csproj" />
    <CSharpProject Include="Plugins\DevILCodecs\Axiom.Plugins.DevILCodecs$(ProjectVariant).csproj" />
    <CSharpProject Include="Plugins\ParticleFX\Axiom.Plugins.ParticleFX$(ProjectVariant).csproj" />
    <CSharpProject Include="Plugins\CGProgramManager\Axiom.Plugins.CGProgramManager$(ProjectVariant).csproj" />
    
   <File Include="Axiom Website.url" />
  
	<!-- Axiom Core -->
  
    <AssemblyFile Include="$(ModuleTempDir)\x86\Axiom.dll">
      <ImagePath>bin\Net35</ImagePath>
    </AssemblyFile>
    <PdbFile Include="$(ModuleTempDir)\x86\Axiom.pdb">
      <ImagePath>bin\Net35</ImagePath>
    </PdbFile>
	<AssemblyFile Include="$(RootDir)\Lib\Managed\XPlatform\ICSharpCode.SharpZipLib\0.84.0.0\ICSharpCode.SharpZipLib.dll" >
      <ImagePath>bin\Net35</ImagePath>
	</AssemblyFile>
	<ConfigFile Include="Engine\bin\x86\Axiom.dll.config" >
      <ImagePath>bin\Net35</ImagePath>
	</ConfigFile>
	<AssemblyFile Include="$(RootDir)\Lib\Managed\CompactFramework\ICSharpCode.SharpZipLib\0.85.4.369\ICSharpCode.SharpZipLib.dll" >
      <ImagePath>bin\Xbox</ImagePath>
	</AssemblyFile>
    <XmlDocFile Include="Engine\bin\x86\Axiom.xml">
      <ImagePath>bin</ImagePath>
    </XmlDocFile>

	<!-- Platforms -->
    <AssemblyFile Include="$(ModuleTempDir)\x86\Axiom.Platforms.Win32.dll">
      <ImagePath>bin\Net35</ImagePath>
    </AssemblyFile>
    <PdbFile Include="$(ModuleTempDir)\x86\Axiom.Platforms.Win32.pdb">
      <ImagePath>bin\Net35</ImagePath>
    </PdbFile>
    <XmlDocFile Include="Platforms\Win32\bin\x86\Axiom.Platforms.Win32.xml">
      <ImagePath>bin</ImagePath>
    </XmlDocFile>

    <AssemblyFile Include="$(ModuleTempDir)\x86\Axiom.Platforms.OpenTK.dll">
      <ImagePath>bin\Net35</ImagePath>
    </AssemblyFile>
    <PdbFile Include="$(ModuleTempDir)\x86\Axiom.Platforms.OpenTK.pdb">
      <ImagePath>bin\Net35</ImagePath>
    </PdbFile>
    <AssemblyFile Include="Platforms\OpenTK\bin\x86\OpenTK.dll">
      <ImagePath>bin\Net35</ImagePath>
    </AssemblyFile>
    <ConfigFile Include="Platforms\OpenTK\bin\x86\OpenTK.dll.config">
      <ImagePath>bin\Net35</ImagePath>
    </ConfigFile>
    <XmlDocFile Include="Platforms\OpenTK\bin\x86\Axiom.Platforms.OpenTK.xml">
      <ImagePath>bin</ImagePath>
    </XmlDocFile>
	
	<!-- RenderSystems -->

    <AssemblyFile Include="$(ModuleTempDir)\x86\Axiom.RenderSystems.DirectX9.dll">
      <ImagePath>bin\Net35</ImagePath>
    </AssemblyFile>
    <PdbFile Include="$(ModuleTempDir)\x86\Axiom.RenderSystems.DirectX9.pdb">
      <ImagePath>bin\Net35</ImagePath>
    </PdbFile>
    <XmlDocFile Include="RenderSystems\DirectX9\bin\x86\Axiom.RenderSystems.DirectX9.xml">
      <ImagePath>bin</ImagePath>
    </XmlDocFile>

    <AssemblyFile Include="$(ModuleTempDir)\x86\Axiom.RenderSystems.OpenGL.dll">
      <ImagePath>bin\Net35</ImagePath>
    </AssemblyFile>
    <PdbFile Include="$(ModuleTempDir)\x86\Axiom.RenderSystems.OpenGL.pdb">
      <ImagePath>bin\Net35</ImagePath>
    </PdbFile>
    <AssemblyFile Include="RenderSystems\OpenGL\bin\x86\OpenTK.Compatibility.dll">
      <ImagePath>bin\Net35</ImagePath>
    </AssemblyFile>
    <AssemblyFile Include="RenderSystems\OpenGL\bin\x86\OpenTK.GLControl.dll">
      <ImagePath>bin\Net35</ImagePath>
    </AssemblyFile>
    <ConfigFile Include="RenderSystems\OpenGL\bin\x86\OpenTK.Compatibility.dll.config">
      <ImagePath>bin\Net35</ImagePath>
    </ConfigFile>
    <XmlDocFile Include="RenderSystems\OpenGL\bin\x86\Axiom.RenderSystems.OpenGL.xml">
      <ImagePath>bin</ImagePath>
    </XmlDocFile>
		
	<!-- SceneManagers -->
    <AssemblyFile Include="$(ModuleTempDir)\x86\Axiom.SceneManagers.PortalConnected.dll">
      <ImagePath>bin\Net35</ImagePath>
    </AssemblyFile>
    <PdbFile Include="$(ModuleTempDir)\x86\Axiom.SceneManagers.PortalConnected.pdb">
      <ImagePath>bin\Net35</ImagePath>
    </PdbFile>
    <XmlDocFile Include="SceneManagers\PCZ\bin\x86\Axiom.SceneManagers.PortalConnected.xml">
      <ImagePath>bin</ImagePath>
    </XmlDocFile>
	
    <AssemblyFile Include="$(ModuleTempDir)\x86\Axiom.SceneManagers.BSP.dll">
      <ImagePath>bin\Net35</ImagePath>
    </AssemblyFile>
    <PdbFile Include="$(ModuleTempDir)\x86\Axiom.SceneManagers.BSP.pdb">
      <ImagePath>bin\Net35</ImagePath>
    </PdbFile>
    <XmlDocFile Include="SceneManagers\BSP\bin\x86\Axiom.SceneManagers.BSP.xml">
      <ImagePath>bin</ImagePath>
    </XmlDocFile>

    <AssemblyFile Include="$(ModuleTempDir)\x86\Axiom.SceneManagers.Octree.dll">
      <ImagePath>bin\Net35</ImagePath>
    </AssemblyFile>
    <PdbFile Include="$(ModuleTempDir)\x86\Axiom.SceneManagers.Octree.pdb">
      <ImagePath>bin\Net35</ImagePath>
    </PdbFile>
    <XmlDocFile Include="SceneManagers\Octree\bin\x86\Axiom.SceneManagers.Octree.xml">
      <ImagePath>bin</ImagePath>
    </XmlDocFile>

	<!-- Plugins -->
	
    <AssemblyFile Include="$(ModuleTempDir)\x86\Axiom.Plugins.FreeImageCodecs.dll">
      <ImagePath>bin\Net35</ImagePath>
    </AssemblyFile>
    <PdbFile Include="$(ModuleTempDir)\x86\Axiom.Plugins.FreeImageCodecs.pdb">
      <ImagePath>bin\Net35</ImagePath>
    </PdbFile>
    <AssemblyFile Include="Plugins\Axiom.Plugins.FreeImageCodecs\bin\x86\FreeImageNET.dll">
      <ImagePath>bin\Net35</ImagePath>
    </AssemblyFile>
    <ConfigFile Include="Plugins\Axiom.Plugins.FreeImageCodecs\bin\x86\FreeImageNET.dll.config">
      <ImagePath>bin\Net35</ImagePath>
    </ConfigFile>
    <XmlDocFile Include="Plugins\Axiom.Plugins.FreeImageCodecs\bin\x86\Axiom.Plugins.FreeImageCodecs.xml">
      <ImagePath>bin</ImagePath>
    </XmlDocFile>
	
    <AssemblyFile Include="$(ModuleTempDir)\x86\Axiom.Plugins.SystemDrawingCodecs.dll">
      <ImagePath>bin\Net35</ImagePath>
    </AssemblyFile>
    <PdbFile Include="$(ModuleTempDir)\x86\Axiom.Plugins.SystemDrawingCodecs.pdb">
      <ImagePath>bin\Net35</ImagePath>
    </PdbFile>
    <XmlDocFile Include="Plugins\Axiom.Plugins.SystemDrawingCodecs\bin\x86\Axiom.Plugins.SystemDrawingCodecs.xml">
      <ImagePath>bin</ImagePath>
    </XmlDocFile>
	
    <AssemblyFile Include="$(ModuleTempDir)\x86\Axiom.Plugins.DevILCodecs.dll">
      <ImagePath>bin\Net35</ImagePath>
    </AssemblyFile>
    <PdbFile Include="$(ModuleTempDir)\x86\Axiom.Plugins.DevILCodecs.pdb">
      <ImagePath>bin\Net35</ImagePath>
    </PdbFile>
    <AssemblyFile Include="Plugins\DevILCodecs\bin\x86\Tao.DevIL.dll">
      <ImagePath>bin\Net35</ImagePath>
    </AssemblyFile>
    <ConfigFile Include="Plugins\DevILCodecs\bin\x86\Tao.DevIL.dll.config">
      <ImagePath>bin\Net35</ImagePath>
    </ConfigFile>
    <XmlDocFile Include="Plugins\DevILCodecs\bin\x86\Axiom.Plugins.DevILCodecs.xml">
      <ImagePath>bin</ImagePath>
    </XmlDocFile>
	
    <AssemblyFile Include="$(ModuleTempDir)\x86\Axiom.Plugins.ParticleFX.dll">
      <ImagePath>bin\Net35</ImagePath>
    </AssemblyFile>
    <PdbFile Include="$(ModuleTempDir)\x86\Axiom.Plugins.ParticleFX.pdb">
      <ImagePath>bin\Net35</ImagePath>
    </PdbFile>
    <XmlDocFile Include="Plugins\ParticleFX\bin\x86\Axiom.Plugins.ParticleFX.xml">
      <ImagePath>bin</ImagePath>
    </XmlDocFile>

    <AssemblyFile Include="$(ModuleTempDir)\x86\Axiom.Plugins.OctreeZone.dll">
      <ImagePath>bin\Net35</ImagePath>
    </AssemblyFile>
    <PdbFile Include="$(ModuleTempDir)\x86\Axiom.Plugins.OctreeZone.pdb">
      <ImagePath>bin\Net35</ImagePath>
    </PdbFile>
    <XmlDocFile Include="Plugins\OctreeZone\bin\x86\Axiom.Plugins.OctreeZone.xml">
      <ImagePath>bin</ImagePath>
    </XmlDocFile>
	
    <AssemblyFile Include="$(ModuleTempDir)\x86\Axiom.Plugins.CGProgramManager.dll">
      <ImagePath>bin\Net35</ImagePath>
    </AssemblyFile>
    <PdbFile Include="$(ModuleTempDir)\x86\Axiom.Plugins.CGProgramManager.pdb">
      <ImagePath>bin\Net35</ImagePath>
    </PdbFile>
    <AssemblyFile Include="Plugins\CGProgramManager\bin\x86\Tao.CG.dll">
      <ImagePath>bin\Net35</ImagePath>
    </AssemblyFile>
    <ConfigFile Include="Plugins\CGProgramManager\bin\x86\Tao.CG.dll.config">
      <ImagePath>bin\Net35</ImagePath>
    </ConfigFile>
    <XmlDocFile Include="Plugins\CGProgramManager\bin\x86\Axiom.Plugins.CGProgramManager.xml">
      <ImagePath>bin</ImagePath>
    </XmlDocFile>
	
	<!--
    <LicenseFile Include="$(RootDir)\Lib\Managed\">
      <ImagePath>licenses</ImagePath>
    </LicenseFile>
    -->

  </ItemGroup>
  
  <ItemGroup Condition="'$(IncludeXna)'=='true'">
    <CSharpProject Include="Engine\Axiom.XBox.csproj"/>
    <CSharpProject Include="RenderSystems\Xna\Axiom.RenderSystems.Xna$(ProjectVariant).csproj"/>
    <CSharpProject Include="RenderSystems\Xna\Axiom.RenderSystems.Xna.XBox.csproj"/>
    <CSharpProject Include="Tools\Axiom.RenderSystems.Xna.Content\Axiom.RenderSystems.Xna.Content.X86$(ProjectVariant).csproj"/>
    <CSharpProject Include="Tools\Axiom.RenderSystems.Xna.Content\Axiom.RenderSystems.Xna.Content.XBox.csproj"/>
    <CSharpProject Include="SceneManagers\BSP\Axiom.SceneManagers.BSP.XBox.csproj" />
    <CSharpProject Include="SceneManagers\Octree\Axiom.SceneManagers.Octree.Xbox.csproj" />
    <CSharpProject Include="Plugins\OctreeZone\Axiom.Plugins.OctreeZone$(ProjectVariant).csproj" />
    <CSharpProject Include="Plugins\ParticleFX\Axiom.Plugins.ParticleFX.Xbox.csproj" />


    <AssemblyFile Include="$(ModuleTempDir)\Xbox\Axiom.dll">
      <ImagePath>bin\Xbox</ImagePath>
    </AssemblyFile>
    <PdbFile Include="$(ModuleTempDir)\Xbox\Axiom.pdb">
      <ImagePath>bin\Xbox</ImagePath>
    </PdbFile>
    <AssemblyFile Include="$(ModuleTempDir)\x86\Axiom.RenderSystems.Xna.dll">
      <ImagePath>bin\Net35</ImagePath>
    </AssemblyFile>
    <PdbFile Include="$(ModuleTempDir)\x86\Axiom.RenderSystems.Xna.pdb">
      <ImagePath>bin\Net35</ImagePath>
    </PdbFile>
    <AssemblyFile Include="$(ModuleTempDir)\Xbox\Axiom.RenderSystems.Xna.dll">
      <ImagePath>bin\Xbox</ImagePath>
    </AssemblyFile>
    <PdbFile Include="$(ModuleTempDir)\Xbox\Axiom.RenderSystems.Xna.pdb">
      <ImagePath>bin\Xbox</ImagePath>
    </PdbFile>
<!--
    <XmlDocFile Include="RenderSystems\Xna\bin\x86\Axiom.RenderSystems.Xna.xml">
      <ImagePath>bin</ImagePath>
    </XmlDocFile>
-->
    <AssemblyFile Include="$(ModuleTempDir)\x86\Axiom.RenderSystems.Xna.Content.dll">
      <ImagePath>bin\Net35</ImagePath>
    </AssemblyFile>
    <PdbFile Include="$(ModuleTempDir)\x86\Axiom.RenderSystems.Xna.Content.pdb">
      <ImagePath>bin\Net35</ImagePath>
    </PdbFile>
    <AssemblyFile Include="$(ModuleTempDir)\Xbox\Axiom.RenderSystems.Xna.Content.dll">
      <ImagePath>bin\Xbox</ImagePath>
    </AssemblyFile>
    <PdbFile Include="$(ModuleTempDir)\Xbox\Axiom.RenderSystems.Xna.Content.pdb">
      <ImagePath>bin\Xbox</ImagePath>
    </PdbFile>
<!--
    <XmlDocFile Include="Tools\Axiom.RenderSystems.Xna.Content\bin\x86\Axiom.RenderSystems.Xna.Content.xml">
      <ImagePath>bin</ImagePath>
    </XmlDocFile>
-->
    <AssemblyFile Include="$(ModuleTempDir)\Xbox\Axiom.SceneManagers.BSP.dll">
      <ImagePath>bin\Xbox</ImagePath>
    </AssemblyFile>
    <PdbFile Include="$(ModuleTempDir)\Xbox\Axiom.SceneManagers.BSP.pdb">
      <ImagePath>bin\Xbox</ImagePath>
    </PdbFile>
    <AssemblyFile Include="$(ModuleTempDir)\Xbox\Axiom.SceneManagers.Octree.dll">
      <ImagePath>bin\Xbox</ImagePath>
    </AssemblyFile>
    <PdbFile Include="$(ModuleTempDir)\Xbox\Axiom.SceneManagers.Octree.pdb">
      <ImagePath>bin\Xbox</ImagePath>
    </PdbFile>
    <AssemblyFile Include="$(ModuleTempDir)\Xbox\Axiom.Plugins.ParticleFX.dll">
      <ImagePath>bin\Xbox</ImagePath>
    </AssemblyFile>
    <PdbFile Include="$(ModuleTempDir)\Xbox\Axiom.Plugins.ParticleFX.pdb">
      <ImagePath>bin\Xbox</ImagePath>
    </PdbFile>
  </ItemGroup>
  
  <Target 
    Name="BeforeImage" 
    DependsOnTargets="AxiomImage_ILMerge;AxiomImage_NoILMerge" />
  
  <Target 
    Name="AxiomImage_ILMerge"
    Condition="'$(NoILMerge)'!='true'"
    Inputs="Engine\bin\Engine.dll;@(AxiomMergeDependency)"
    Outputs="$(ModuleTempDir)\Axiom.dll">

    <Message 
      Text="Running ILMerge on Axiom.dll..."
      Importance="High" />

    <Exec 
      Command="&quot;$(ToolsDir)\ILMerge\ILMerge.exe&quot; &quot;Gallio\bin\Gallio.dll&quot; @(AxiomMergeDependency->'&quot;%(Identity)&quot;', ' ') /internalize &quot;/out:$(ModuleTempDir)\Axiom.dll&quot;" />
	      
  </Target>

  <Target 
    Name="AxiomImage_NoILMerge"
    Condition="'$(NoILMerge)'=='true'">
    
    <Copy 
      SourceFiles="@(Axiom_x86_SourceFile)"
	  
      DestinationFolder="$(ModuleTempDir)\x86\" />
	  
    <Copy 
      SourceFiles="@(Axiom_Xbox_SourceFile)"
      DestinationFolder="$(ModuleTempDir)\Xbox\" 
	 />

	<Copy 
      SourceFiles="@(GallioMergeDependency)"
      DestinationFolder="$(ModuleImageDir)\bin" />
      
  </Target>

  <ItemGroup>
    <AxiomMergeDependency Include="Gallio\bin\Mono.Cecil.dll" />
    <AxiomMergeDependency Include="Gallio\bin\ICSharpCode.SharpZipLib.dll" />
    <AxiomMergeDependency Include="Gallio\bin\Gallio.ReflectionShim.dll" />
    <AxiomMergeDependency Include="Gallio\bin\Microsoft.Cci.MetadataHelper.dll" />
    <AxiomMergeDependency Include="Gallio\bin\Microsoft.Cci.MetadataModel.dll" />
    <AxiomMergeDependency Include="Gallio\bin\Microsoft.Cci.PdbReader.dll" />
    <AxiomMergeDependency Include="Gallio\bin\Microsoft.Cci.PeReader.dll" />
    <AxiomMergeDependency Include="Gallio\bin\Microsoft.Cci.SourceModel.dll" />
  </ItemGroup>

  <ItemGroup>
	<Axiom_x86_SourceFile Include="Engine\bin\x86\Axiom.dll" />
	<Axiom_x86_SourceFile Include="Engine\bin\x86\Axiom.pdb" />
	<Axiom_x86_SourceFile Include="Platforms\Win32\bin\x86\Axiom.Platforms.Win32.dll" />
	<Axiom_x86_SourceFile Include="Platforms\Win32\bin\x86\Axiom.Platforms.Win32.pdb" />
	<Axiom_x86_SourceFile Include="Platforms\OpenTK\bin\x86\Axiom.Platforms.OpenTK.dll" />
	<Axiom_x86_SourceFile Include="Platforms\OpenTK\bin\x86\Axiom.Platforms.OpenTK.pdb" />
	<Axiom_x86_SourceFile Include="RenderSystems\DirectX9\bin\x86\Axiom.RenderSystems.DirectX9.dll" />
	<Axiom_x86_SourceFile Include="RenderSystems\DirectX9\bin\x86\Axiom.RenderSystems.DirectX9.pdb" />
	<Axiom_x86_SourceFile Include="RenderSystems\OpenGL\bin\x86\Axiom.RenderSystems.OpenGL.dll" />
	<Axiom_x86_SourceFile Include="RenderSystems\OpenGL\bin\x86\Axiom.RenderSystems.OpenGL.pdb" />
	<Axiom_x86_SourceFile Include="RenderSystems\Xna\bin\x86\Axiom.RenderSystems.Xna.dll" />
	<Axiom_x86_SourceFile Include="RenderSystems\Xna\bin\x86\Axiom.RenderSystems.Xna.pdb" />
	<Axiom_x86_SourceFile Include="Tools\Axiom.RenderSystems.Xna.Content\bin\x86\Axiom.RenderSystems.Xna.Content.dll" />
	<Axiom_x86_SourceFile Include="Tools\Axiom.RenderSystems.Xna.Content\bin\x86\Axiom.RenderSystems.Xna.Content.pdb" />
	<Axiom_x86_SourceFile Include="SceneManagers\BSP\bin\x86\Axiom.SceneManagers.BSP.dll" />
	<Axiom_x86_SourceFile Include="SceneManagers\BSP\bin\x86\Axiom.SceneManagers.BSP.pdb" />
	<Axiom_x86_SourceFile Include="SceneManagers\Octree\bin\x86\Axiom.SceneManagers.Octree.dll" />
	<Axiom_x86_SourceFile Include="SceneManagers\Octree\bin\x86\Axiom.SceneManagers.Octree.pdb" />
	<Axiom_x86_SourceFile Include="SceneManagers\PCZ\bin\x86\Axiom.SceneManagers.PortalConnected.dll" />
	<Axiom_x86_SourceFile Include="SceneManagers\PCZ\bin\x86\Axiom.SceneManagers.PortalConnected.pdb" />
	<Axiom_x86_SourceFile Include="Plugins\Axiom.Plugins.FreeImageCodecs\bin\x86\Axiom.Plugins.FreeImageCodecs.dll" />
	<Axiom_x86_SourceFile Include="Plugins\Axiom.Plugins.FreeImageCodecs\bin\x86\Axiom.Plugins.FreeImageCodecs.pdb" />
	<Axiom_x86_SourceFile Include="Plugins\Axiom.Plugins.SystemDrawingCodecs\bin\x86\Axiom.Plugins.SystemDrawingCodecs.dll" />
	<Axiom_x86_SourceFile Include="Plugins\Axiom.Plugins.SystemDrawingCodecs\bin\x86\Axiom.Plugins.SystemDrawingCodecs.pdb" />
	<Axiom_x86_SourceFile Include="Plugins\DevILCodecs\bin\x86\Axiom.Plugins.DevILCodecs.dll" />
	<Axiom_x86_SourceFile Include="Plugins\DevILCodecs\bin\x86\Axiom.Plugins.DevILCodecs.pdb" />
	<Axiom_x86_SourceFile Include="Plugins\ParticleFX\bin\x86\Axiom.Plugins.ParticleFX.dll" />
	<Axiom_x86_SourceFile Include="Plugins\ParticleFX\bin\x86\Axiom.Plugins.ParticleFX.pdb" />
	<Axiom_x86_SourceFile Include="Plugins\OctreeZone\bin\x86\Axiom.Plugins.OctreeZone.dll" />
	<Axiom_x86_SourceFile Include="Plugins\OctreeZone\bin\x86\Axiom.Plugins.OctreeZone.pdb" />
	<Axiom_x86_SourceFile Include="Plugins\CGProgramManager\bin\x86\Axiom.Plugins.CGProgramManager.dll" />
	<Axiom_x86_SourceFile Include="Plugins\CGProgramManager\bin\x86\Axiom.Plugins.CGProgramManager.pdb" />
  </ItemGroup>
  
  <ItemGroup>
	<Axiom_Xbox_SourceFile Include="Engine\bin\Xbox\Axiom.dll" />
	<Axiom_Xbox_SourceFile Include="Engine\bin\Xbox\Axiom.pdb" />
	<Axiom_Xbox_SourceFile Include="RenderSystems\Xna\bin\XBox\Axiom.RenderSystems.Xna.dll" />
	<Axiom_Xbox_SourceFile Include="RenderSystems\Xna\bin\XBox\Axiom.RenderSystems.Xna.pdb" />
	<Axiom_Xbox_SourceFile Include="Tools\Axiom.RenderSystems.Xna.Content\bin\XBox\Axiom.RenderSystems.Xna.Content.dll" />
	<Axiom_Xbox_SourceFile Include="Tools\Axiom.RenderSystems.Xna.Content\bin\XBox\Axiom.RenderSystems.Xna.Content.pdb" />
	<Axiom_Xbox_SourceFile Include="SceneManagers\BSP\bin\Xbox\Axiom.SceneManagers.BSP.dll" />
	<Axiom_Xbox_SourceFile Include="SceneManagers\BSP\bin\Xbox\Axiom.SceneManagers.BSP.pdb" />
	<Axiom_Xbox_SourceFile Include="SceneManagers\Octree\bin\Xbox\Axiom.SceneManagers.Octree.dll" />
	<Axiom_Xbox_SourceFile Include="SceneManagers\Octree\bin\Xbox\Axiom.SceneManagers.Octree.pdb" />
	<Axiom_Xbox_SourceFile Include="Plugins\ParticleFX\bin\Xbox\Axiom.Plugins.ParticleFX.dll" />
	<Axiom_Xbox_SourceFile Include="Plugins\ParticleFX\bin\Xbox\Axiom.Plugins.ParticleFX.pdb" />
  </ItemGroup>
  
  <Target Name="BeforeDist"
		  DependsOnTargets="AxiomDist_NuGetPackage" />
		  
  <ItemGroup>
    <Axiom_NuGetPackage Include="NuGet Package\*.nuspec" />
	<Axiom_Package_Tool Include="NuGet Package\tools\*.*" />
  </ItemGroup>
  
  <Target Name="AxiomDist_NuGetPackage" >
	<!-- 
		  Inputs="@(Axiom_NuGetPackage)"
		  Outputs="@(Axiom_NuGetPackage->'$(ModuleTempDir)\packages\%(Identity)')"
	-->
    
    <Copy SourceFiles="@(Axiom_NuGetPackage)"
		  DestinationFolder="$(ModuleTempDir)\packages\%(Axiom_NuGetPackage.Filename)" />
    <Copy SourceFiles="@(Axiom_Package_Tool)"
		  DestinationFolder="$(ModuleTempDir)\packages\tools" />

    <Version VersionFile="version.txt" >
		<Output TaskParameter="Major" PropertyName="Major" />
		<Output TaskParameter="Minor" PropertyName="Minor" />
		<Output TaskParameter="Build" PropertyName="Revision" />
		<Output TaskParameter="Revision" PropertyName="BuildDate" />
    </Version>
	
    <Message Text="Version from file: $(Major).$(Minor).$(Revision).$(BuildDate)"/>

    <FileUpdate Files="$(ModuleTempDir)\packages\%(Axiom_NuGetPackage.Filename)\%(Axiom_NuGetPackage.Filename).nuspec"
				RegEx='\$id\$'
				ReplacementText='%(Axiom_NuGetPackage.Filename)' />
				
    <FileUpdate Files="$(ModuleTempDir)\packages\%(Axiom_NuGetPackage.Filename)\%(Axiom_NuGetPackage.Filename).nuspec"
				RegEx='\$version\$'
				ReplacementText='$(Major).$(Minor).$(Revision).$(BuildDate)' />

    <FileUpdate Files="$(ModuleTempDir)\packages\%(Axiom_NuGetPackage.Filename)\%(Axiom_NuGetPackage.Filename).nuspec"
				RegEx='\$author\$'
				ReplacementText='Axiom Project Team' />	
				
    <FileUpdate Files="$(ModuleTempDir)\packages\%(Axiom_NuGetPackage.Filename)\%(Axiom_NuGetPackage.Filename).nuspec"
				RegEx='\$description\$'
				ReplacementText='%(Axiom_NuGetPackage.Filename)' />	
	
	<MakeDir Directories="$(ModuleDistDir)\Packages" />
	
	<EXEC WorkingDirectory="$(ModuleTempDir)\packages\%(Axiom_NuGetPackage.Filename)"
		  Command="$(ToolsDir)\Nuget\Nuget.exe pack $(ModuleTempDir)\packages\%(Axiom_NuGetPackage.Filename)\%(Axiom_NuGetPackage.Filename).nuspec -OutputDirectory $(ModuleDistDir)\Packages" />
  </Target>
		  
</Project>