<Project ToolsVersion="3.5" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />

  <ItemGroup>
    <Module Include="Engine\axiom.module" />
    
    <Module Include="Platforms\Win32\axiom.platform.win32.module" Condition="'$(Platform)'=='x86'" />
    <Module Include="Platforms\OpenTK\axiom.platform.opentk.module" Condition="'$(Platform)'=='x86'" />

    <Module Include="RenderSystems\DirectX9\axiom.rendersystem.directx9.module" Condition="'$(Platform)'=='x86'" />
    <Module Include="RenderSystems\OpenGL\axiom.rendersystem.opengl.win32.module" Condition="'$(Platform)'=='x86'" />
    <Module Include="RenderSystems\OpenGL\axiom.rendersystem.opengl.opentk.module" Condition="'$(Platform)'=='x86'" />
    <Module Include="RenderSystems\Xna\axiom.rendersystem.xna.module" />
      <Module Include="Tools\Axiom.RenderSystems.Xna.Content\axiom.tool.xna.content.module" />

    <Module Include="SceneManagers\Bsp\axiom.scenemanager.bsp.module" Condition="'$(Platform)'=='x86'"/>
    <Module Include="SceneManagers\Octree\axiom.scenemanager.octree.module" Condition="'$(Platform)'=='x86'"/>
    <Module Include="SceneManagers\PCZ\axiom.scenemanager.pcz.module" Condition="'$(Platform)'=='x86'" />
      <Module Include="Plugins\OctreeZone\axiom.plugin.octreezone.module" Condition="'$(Platform)'=='x86'" />

    <Module Include="Plugins\Axiom.Plugins.SystemDrawingCodecs\axiom.plugin.systemdrawingcodecs.module" Condition="'$(Platform)'=='x86'" />
    <Module Include="Plugins\CgProgramManager\axiom.plugin.cgprogrammanager.module" Condition="'$(Platform)'=='x86'" />
    <Module Include="Plugins\DevILCodecs\axiom.plugin.devilcodecs.module" Condition="'$(Platform)'=='x86'" />
    <Module Include="Plugins\ParticleFX\axiom.plugin.particlefx.module" />

  </ItemGroup>

</Project>
