<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <PropertyGroup>
		<Version Condition="'$(Version)'==''">0.8.0.0</Version>
		
		<AssemblyVersion>$(AssemblyVersion)</AssemblyVersion>
		<AssemblyVersion Condition="'$(AssemblyVersion)'==''">$(Version)</AssemblyVersion>

		<FileVersion>$(FileVersion)</FileVersion>
		<FileVersion Condition="'$(FileVersion)'==''">$(Version)</FileVersion>		
	</PropertyGroup>
</Project>