#region LGPL License

/*
Axiom Graphics Engine Library
Copyright ? 2003-2012 Axiom Rendering Engine Project Team

The overall design, and a majority of the core engine and rendering code 
contained within this library is a derivative of the open source Object Oriented 
Graphics Engine OGRE, which can be found at http://ogre.sourceforge.net.  
Many thanks to the OGRE team for maintaining such a high quality project.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
*/

#endregion

using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute( false )]
[assembly: CLSCompliantAttribute( false )]
#if DEBUG
[assembly: AssemblyConfiguration("https://axiomengine.svn.sourceforge.net/svnroot/axiomengine/branches/v0.8.0.0/, Mixed Revisions, Local Modifications, Debug")]
#else
[assembly: AssemblyConfiguration("https://axiomengine.svn.sourceforge.net/svnroot/axiomengine/branches/v0.8.0.0/, Mixed Revisions, Local Modifications, Release")]
#endif
[assembly: AssemblyCompanyAttribute( "Axiom Rendering Engine Project Team (http://axiom3d.net)" )]
[assembly: AssemblyProductAttribute( "Axiom Rendering Engine" )]
[assembly: AssemblyCopyrightAttribute( "Copyright ? 2003-2012 Axiom Rendering Engine Project Team." )]
[assembly: AssemblyTrademarkAttribute( "" )]
[assembly: AssemblyCultureAttribute( "" )]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Revision Number
//      YearWeekDayOfWeek
//

[assembly: AssemblyVersion( /* Major.Minor.Revision.YearWeekDay */ "0.8.3376.12322" )]
#if !( XBOX || XBOX360 )
[assembly: AssemblyFileVersion( /* Major.Minor.Revision.YearWeekDay */ "0.8.3376.12322" )]
#endif

[assembly: AssemblyInformationalVersion( /* Major.Minor.Revision.YearWeekDay */ "0.8.3376.12322" )]
