#region LGPL License

/*
Axiom Graphics Engine Library
Copyright ? 2003-2012 Axiom Rendering Engine Project Team

The overall design, and a majority of the core engine and rendering code 
contained within this library is a derivative of the open source Object Oriented 
Graphics Engine OGRE, which can be found at http://ogre.sourceforge.net.  
Many thanks to the OGRE team for maintaining such a high quality project.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
*/

#endregion

using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisible( false )]
[assembly: CLSCompliant( false )]

[assembly: AssemblyCompany( "Axiom Rendering Engine Project Team (http://axiom3d.net)" )]
[assembly: AssemblyProduct( "Axiom Rendering Engine" )]
[assembly: AssemblyCopyright("Copyright © 2003-2011 Axiom Rendering Engine Project Team.")]
[assembly: AssemblyTrademark( "" )]
[assembly: AssemblyCulture( "" )]

[assembly: AssemblyVersion("0.8.5000.0")]
[assembly: AssemblyFileVersion("0.8.5000.0")]
[assembly: AssemblyInformationalVersion("0.8.5000-beta.1+366.Branch.release/v0.8.5000.Sha.18ad90d74b6209b05a69f599f8e0378d336fef9d")]
