using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(false)]
[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyCompanyAttribute("Axiom Rendering Engine Project Team (http://axiomengine.sourceforge.net)")]
[assembly: AssemblyProductAttribute("Axiom Rendering Engine")]
[assembly: AssemblyCopyrightAttribute("Copyright (C) 2005-2009 Axiom Rendering Engine Project Team.")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
//[assembly: AssemblyVersionAttribute("0.7.5.0")]
[assembly: AssemblyInformationalVersionAttribute("0.7.5.0")]

