<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <Import Project="$(RootDir)\tools\build\Module.targets" />

  <PropertyGroup>
    <AxiomBuildTasksPath>$(RootDir)\tools\build\</AxiomBuildTasksPath>
  </PropertyGroup>
  <ItemGroup>
    <Svn Include="$(RootDir)" />
    <Version Include="$(SourceDir)\Axiom\version.txt" />
    <AssemblyInfoTemplate Include="Axiom.Game.DX9\Axiom.Game.DX9.vstemplate.in" >
      <OutputFile>Axiom.Game.DX9\Axiom.Game.DX9.vstemplate</OutputFile>
    </AssemblyInfoTemplate>
    <AssemblyInfoTemplate Include="AxiomTemplatesVSIX\AxiomTemplatesVSIX.csproj.in" >
      <OutputFile>AxiomTemplatesVSIX\AxiomTemplatesVSIX.csproj</OutputFile>
    </AssemblyInfoTemplate>
    <AssemblyInfoTemplate Include="AxiomTemplatesVSIX\source.extension.vsixmanifest.in" >
      <OutputFile>AxiomTemplatesVSIX\source.extension.vsixmanifest</OutputFile>
    </AssemblyInfoTemplate>
  </ItemGroup>
  <Import Project="$(AxiomBuildTasksPath)\Axiom.Build.Version.targets" />

  <Target Name="BeforePrecondition"
    DependsOnTargets="UpdateVersionTxtFile" />

  <Target Name="AfterDist"
          DependsOnTargets="DistTemplates" />
  
  <Target Name="DistTemplates"
          DependsOnTargets="DistVS2010Templates" />

  <Target Name="BuildVS2010Templates">
    <!-- Copy NuGet Packages from Build folder to local Project Folder -->
    <!-- Update Package names -->
    <!-- Build -->
  </Target>

  <Target Name="PrepareToDistTemplates">
    <ItemGroup>
      <NuGetPackage Include="Axiom.nupkg" />
      <NuGetPackage Include="Axiom.Platforms.Win32.nupkg" />
      <NuGetPackage Include="Axiom.RenderSystems.DirectX9.nupkg" />
      <NuGetPackage Include="Axiom.Plugins.FreeImageCodecs.nupkg" />

    </ItemGroup>

    <Copy SourceFiles="@(NuGetPackage->'$(ModulesDir)\Axiom\dist\packages\%(Filename).$(AssemblyVersion)%(Extension)')"
          DestinationFiles="@(NuGetPackage->'$(SourceDir)\ProjectTemplates\AxiomTemplatesVSIX\packages\%(Filename).$(AssemblyVersion)%(Extension)')"
          SkipUnchangedFiles="true" />
  </Target>
  
  <Target Name="DistVS2010Templates"
        DependsOnTargets="PrepareToDistTemplates">
    <Message Text="Building Vsix Template Package.."
             Importance="High" />

    <MSBuild Projects="$(SourceDir)\ProjectTemplates\AxiomTemplates.sln"
             Properties="FileVersion=$(AssemblyVersion)"
             Targets="Build" />

    <Copy DestinationFiles="$(ModulesDir)\Axiom.Templates\dist\packages\AxiomTemplates.vsix"
          SourceFiles="$(SourceDir)\ProjectTemplates\AxiomTemplatesVSIX\bin\Release\AxiomTemplates.vsix"
          SkipUnchangedFiles="true" />

  </Target>

</Project>