<Project ToolsVersion="3.5" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />

  <PropertyGroup>
    <ProjectBase>Axiom.RenderSystems.OpenGL.OpenTK</ProjectBase>
    <ProjectFile Condition="'$(Platform)'=='x86'">$(ProjectBase).csproj</ProjectFile>
    <ProjectFile Condition="'$(Platform)'=='Xbox'">$(ProjectBase).$(Platform).csproj</ProjectFile>
    <ImagePath>bin\$(Platform)\$(Configuration)</ImagePath>
    <OutputPath>bin\$(Platform)\$(Configuration)</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <!-- The path of a project to be built. -->
    <CSharpProject Include="$(ProjectFile)" >
      <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
      <Platform Condition="'$(Platform)'=='Xbox'">$(Platform) 360</Platform>
      <OutputPath>$(OutputPath)</OutputPath>
    </CSharpProject>

    <!-- The path of a built file to be copied to the "image" directory. -->
    <File Include="bin\$(Platform)\$(Configuration)\$(ProjectBase).dll">
      <ImagePath>$(ImagePath)</ImagePath>
    </File>

    <File Include="bin\$(Platform)\$(Configuration)\$(ProjectBase).pdb" Condition="'$(Configuration)'=='Debug'">
      <ImagePath>$(ImagePath)</ImagePath>
    </File>

    <File Include="bin\$(Platform)\$(Configuration)\$(ProjectBase).XML"  Condition="'$(Configuration)'=='Release'">
      <ImagePath>$(ImagePath)</ImagePath>
    </File>

  </ItemGroup>

</Project>