<Project ToolsVersion="3.5" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />

  <PropertyGroup>
    <ProjectBase>Axiom.Demos</ProjectBase>
    <ProjectFile Condition="'$(Platform)'=='x86'">$(ProjectBase).csproj</ProjectFile>
    <ProjectFile Condition="'$(Platform)'=='Xbox'">$(ProjectBase).$(Platform).csproj</ProjectFile>
    <ImagePath>samples\$(Platform)</ImagePath>
    <OutputPath>samples\$(Platform)</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <!-- The path of a project to be built. -->
    <CSharpProject Include="$(ProjectFile)" >
      <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
      <Platform Condition="'$(Platform)'=='Xbox'">$(Platform) 360</Platform>
      <OutputPath>$(OutputPath)</OutputPath>
      <WarningLevel Condition="'$(Configuration)'=='Debug'">4</WarningLevel>
      <WarningLevel Condition="'$(Configuration)'=='Release'">0</WarningLevel>
    </CSharpProject>

    <!-- The path of a built file to be copied to the "image" directory. -->
    <File Include="$(OutputPath)\$(ProjectBase).dll" Condition="'$(Platform)'!='x86'" >
      <ImagePath>$(ImagePath)</ImagePath>
    </File>

  </ItemGroup>

</Project>
