<Project ToolsVersion="3.5" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />

  <PropertyGroup>
    <RenderSystem>$(RenderSystem)</RenderSystem>
    <ProjectBase>Axiom.Demos.Browser.WinForm</ProjectBase>
    <ProjectFile Condition="'$(Platform)'=='x86'">$(ProjectBase).$(RenderSystem).csproj</ProjectFile>
    <ProjectFile Condition="'$(Platform)'=='Xbox'">$(ProjectBase).$(Platform).csproj</ProjectFile>
    <ImagePath>samples\$(RenderSystem)</ImagePath>
    <OutputPath>bin\$(Platform)\$(Configuration)</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <!-- The path of a project to be built. -->
    <CSharpProject Include="$(ProjectFile)" >
      <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
      <Platform Condition="'$(Platform)'=='Xbox'">$(Platform) 360</Platform>
      <OutputPath>$(OutputPath)</OutputPath>
      <WarningLevel Condition="'$(Configuration)'=='Debug'">4</WarningLevel>
      <WarningLevel Condition="'$(Configuration)'=='Release'">0</WarningLevel>
    </CSharpProject>

    <!-- The path of a built file to be copied to the "image" directory. -->
    <File Include="$(OutputPath)\$(ProjectBase).exe" Condition="'$(Platform)'!='x86'" >
      <ImagePath>$(ImagePath)</ImagePath>
    </File>
    
    <File Include="$(OutputPath)\$(ProjectBase).exe" Condition="'$(Platform)'=='x86'" >
      <ImagePath>$(ImagePath)</ImagePath>
    </File>

    <File Include="$(OutputPath)\Axiom.Demos.dll" Condition="'$(Platform)'=='x86'" >
      <ImagePath>$(ImagePath)</ImagePath>
    </File>

    <!-- Binary Dependencies -->

    <!-- RenderSystem + Platform Manager -->

    <File Include="$(ImageDir)\bin\$(Platform)\$(Configuration)\Axiom.Platforms.Win32.dll" Condition="'$(RenderSystem)'=='DirectX'" >
      <ImagePath>$(ImagePath)</ImagePath>
    </File>

    <File Include="$(ImageDir)\bin\$(Platform)\$(Configuration)\Axiom.RenderSystems.DirectX9.dll" Condition="'$(RenderSystem)'=='DirectX'" >
      <ImagePath>$(ImagePath)</ImagePath>
    </File>
    
    <File Include="$(ImageDir)\bin\$(Platform)\$(Configuration)\Axiom.RenderSystems.Xna.dll" Condition="'$(RenderSystem)'=='Xna'" >
      <ImagePath>$(ImagePath)</ImagePath>
    </File>
    <File Include="$(ImageDir)\bin\$(Platform)\$(Configuration)\Axiom.RenderSystems.Xna.Content.dll" Condition="'$(RenderSystem)'=='Xna'" >
      <ImagePath>$(ImagePath)</ImagePath>
    </File>

    <File Include="$(ImageDir)\bin\$(Platform)\$(Configuration)\Axiom.Platforms.OpenTK.dll" Condition="'$(RenderSystem)'=='OpenGL'" >
      <ImagePath>$(ImagePath)</ImagePath>
    </File>

    <File Include="$(ImageDir)\bin\$(Platform)\$(Configuration)\Axiom.RenderSystems.OpenGL.OpenTK.dll" Condition="'$(RenderSystem)'=='OpenGL'" >
      <ImagePath>$(ImagePath)</ImagePath>
    </File>

    <!-- Scene Managers -->
    
    <File Include="$(ImageDir)\bin\$(Platform)\$(Configuration)\Axiom.SceneManagers.Bsp.dll" >
      <ImagePath>$(ImagePath)</ImagePath>
    </File>

    <File Include="$(ImageDir)\bin\$(Platform)\$(Configuration)\Axiom.SceneManagers.Octree.dll" >
      <ImagePath>$(ImagePath)</ImagePath>
    </File>

    <File Include="$(ImageDir)\bin\$(Platform)\$(Configuration)\Axiom.SceneManagers.PortalConnected.dll" Condition="'$(Platform)'=='x86'" >
      <ImagePath>$(ImagePath)</ImagePath>
    </File>

    <!-- Plugins -->

    <File Include="$(ImageDir)\bin\$(Platform)\$(Configuration)\Axiom.Plugins.ParticleFX.dll" >
      <ImagePath>$(ImagePath)</ImagePath>
    </File>

    <File Include="$(ImageDir)\bin\$(Platform)\$(Configuration)\Axiom.Plugins.DeviLCodecs.dll" Condition="'$(Platform)'=='x86'" >
      <ImagePath>$(ImagePath)</ImagePath>
    </File>

    <File Include="$(ImageDir)\bin\$(Platform)\$(Configuration)\Axiom.Plugins.CgProgramManager.dll" Condition="'$(Platform)'=='x86'" >
      <ImagePath>$(ImagePath)</ImagePath>
    </File>

  </ItemGroup>

</Project>
