<Project ToolsVersion="3.5" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MetaBuildBinDir)\MetaBuild.Module.targets" />

  <Target Name="AfterImage">
    <RemoveDir Directories="$(ImageDir)\MetaBuild" />

    <SvnExport RepositoryPath="$(ModuleDir)"
               LocalPath="$(ImageDir)\MetaBuild" />
  </Target>

  <Target Name="AfterDist">
    <ItemGroup>
      <_MetaBuildFiles Include="$(ImageDir)\MetaBuild\**\*" />
    </ItemGroup>

    <Zip Files="@(_MetaBuildFiles)"
	 WorkingDirectory="$(ImageDir)\MetaBuild"
         Condition="'@(_MetaBuildFiles)'!=''"
         ZipFileName="$(DistDir)\MetaBuild-$(Version).zip" />
  </Target>
</Project>
